create schema IF NOT EXISTS eshop;

drop table if exists eshop.customer cascade;
drop table if exists eshop."order" cascade;
drop table if exists eshop.product cascade;

CREATE TABLE IF NOT EXISTS eshop.customer
(
    customerId bigint generated by default as identity NOT NULL PRIMARY KEY,
    dateAdded  TIMESTAMP    DEFAULT NULL,
    email      varchar(255) DEFAULT NULL,
    name       varchar(255) DEFAULT NULL,
    password   varchar(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS eshop."order"
(
    orderId    bigint generated by default as identity NOT NULL PRIMARY KEY,
    customerId bigint DEFAULT NULL,
    price      int NOT NULL,
    productId  bigint DEFAULT NULL,
    quantity   int NOT NULL
);

CREATE TABLE IF NOT EXISTS eshop.product
(
    productId bigint generated by default as identity NOT NULL PRIMARY KEY,
    name      varchar(255) DEFAULT NULL,
    quantity  varchar(255) DEFAULT NULL,
    price     smallint     DEFAULT NULL
);